//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	demo "github.com/guodoliu/apiserver/pkg/apis/demo"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Foo)(nil), (*demo.Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Foo_To_demo_Foo(a.(*Foo), b.(*demo.Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*demo.Foo)(nil), (*Foo)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_demo_Foo_To_v1alpha1_Foo(a.(*demo.Foo), b.(*Foo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooCondition)(nil), (*demo.FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooCondition_To_demo_FooCondition(a.(*FooCondition), b.(*demo.FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*demo.FooCondition)(nil), (*FooCondition)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_demo_FooCondition_To_v1alpha1_FooCondition(a.(*demo.FooCondition), b.(*FooCondition), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooConfig)(nil), (*demo.FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooConfig_To_demo_FooConfig(a.(*FooConfig), b.(*demo.FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*demo.FooConfig)(nil), (*FooConfig)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_demo_FooConfig_To_v1alpha1_FooConfig(a.(*demo.FooConfig), b.(*FooConfig), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooList)(nil), (*demo.FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooList_To_demo_FooList(a.(*FooList), b.(*demo.FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*demo.FooList)(nil), (*FooList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_demo_FooList_To_v1alpha1_FooList(a.(*demo.FooList), b.(*FooList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooSpec)(nil), (*demo.FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooSpec_To_demo_FooSpec(a.(*FooSpec), b.(*demo.FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*demo.FooSpec)(nil), (*FooSpec)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_demo_FooSpec_To_v1alpha1_FooSpec(a.(*demo.FooSpec), b.(*FooSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*FooStatus)(nil), (*demo.FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_FooStatus_To_demo_FooStatus(a.(*FooStatus), b.(*demo.FooStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*demo.FooStatus)(nil), (*FooStatus)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_demo_FooStatus_To_v1alpha1_FooStatus(a.(*demo.FooStatus), b.(*FooStatus), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Foo_To_demo_Foo(in *Foo, out *demo.Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_FooSpec_To_demo_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_FooStatus_To_demo_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_Foo_To_demo_Foo is an autogenerated conversion function.
func Convert_v1alpha1_Foo_To_demo_Foo(in *Foo, out *demo.Foo, s conversion.Scope) error {
	return autoConvert_v1alpha1_Foo_To_demo_Foo(in, out, s)
}

func autoConvert_demo_Foo_To_v1alpha1_Foo(in *demo.Foo, out *Foo, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_demo_FooSpec_To_v1alpha1_FooSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_demo_FooStatus_To_v1alpha1_FooStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_demo_Foo_To_v1alpha1_Foo is an autogenerated conversion function.
func Convert_demo_Foo_To_v1alpha1_Foo(in *demo.Foo, out *Foo, s conversion.Scope) error {
	return autoConvert_demo_Foo_To_v1alpha1_Foo(in, out, s)
}

func autoConvert_v1alpha1_FooCondition_To_demo_FooCondition(in *FooCondition, out *demo.FooCondition, s conversion.Scope) error {
	out.Type = demo.FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_v1alpha1_FooCondition_To_demo_FooCondition is an autogenerated conversion function.
func Convert_v1alpha1_FooCondition_To_demo_FooCondition(in *FooCondition, out *demo.FooCondition, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooCondition_To_demo_FooCondition(in, out, s)
}

func autoConvert_demo_FooCondition_To_v1alpha1_FooCondition(in *demo.FooCondition, out *FooCondition, s conversion.Scope) error {
	out.Type = FooConditionType(in.Type)
	out.Status = v1.ConditionStatus(in.Status)
	return nil
}

// Convert_demo_FooCondition_To_v1alpha1_FooCondition is an autogenerated conversion function.
func Convert_demo_FooCondition_To_v1alpha1_FooCondition(in *demo.FooCondition, out *FooCondition, s conversion.Scope) error {
	return autoConvert_demo_FooCondition_To_v1alpha1_FooCondition(in, out, s)
}

func autoConvert_v1alpha1_FooConfig_To_demo_FooConfig(in *FooConfig, out *demo.FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Msg1 = in.Msg1
	return nil
}

// Convert_v1alpha1_FooConfig_To_demo_FooConfig is an autogenerated conversion function.
func Convert_v1alpha1_FooConfig_To_demo_FooConfig(in *FooConfig, out *demo.FooConfig, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooConfig_To_demo_FooConfig(in, out, s)
}

func autoConvert_demo_FooConfig_To_v1alpha1_FooConfig(in *demo.FooConfig, out *FooConfig, s conversion.Scope) error {
	out.Msg = in.Msg
	out.Msg1 = in.Msg1
	return nil
}

// Convert_demo_FooConfig_To_v1alpha1_FooConfig is an autogenerated conversion function.
func Convert_demo_FooConfig_To_v1alpha1_FooConfig(in *demo.FooConfig, out *FooConfig, s conversion.Scope) error {
	return autoConvert_demo_FooConfig_To_v1alpha1_FooConfig(in, out, s)
}

func autoConvert_v1alpha1_FooList_To_demo_FooList(in *FooList, out *demo.FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]demo.Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_FooList_To_demo_FooList is an autogenerated conversion function.
func Convert_v1alpha1_FooList_To_demo_FooList(in *FooList, out *demo.FooList, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooList_To_demo_FooList(in, out, s)
}

func autoConvert_demo_FooList_To_v1alpha1_FooList(in *demo.FooList, out *FooList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]Foo)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_demo_FooList_To_v1alpha1_FooList is an autogenerated conversion function.
func Convert_demo_FooList_To_v1alpha1_FooList(in *demo.FooList, out *FooList, s conversion.Scope) error {
	return autoConvert_demo_FooList_To_v1alpha1_FooList(in, out, s)
}

func autoConvert_v1alpha1_FooSpec_To_demo_FooSpec(in *FooSpec, out *demo.FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_v1alpha1_FooConfig_To_demo_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_FooSpec_To_demo_FooSpec is an autogenerated conversion function.
func Convert_v1alpha1_FooSpec_To_demo_FooSpec(in *FooSpec, out *demo.FooSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooSpec_To_demo_FooSpec(in, out, s)
}

func autoConvert_demo_FooSpec_To_v1alpha1_FooSpec(in *demo.FooSpec, out *FooSpec, s conversion.Scope) error {
	out.Image = in.Image
	if err := Convert_demo_FooConfig_To_v1alpha1_FooConfig(&in.Config, &out.Config, s); err != nil {
		return err
	}
	return nil
}

// Convert_demo_FooSpec_To_v1alpha1_FooSpec is an autogenerated conversion function.
func Convert_demo_FooSpec_To_v1alpha1_FooSpec(in *demo.FooSpec, out *FooSpec, s conversion.Scope) error {
	return autoConvert_demo_FooSpec_To_v1alpha1_FooSpec(in, out, s)
}

func autoConvert_v1alpha1_FooStatus_To_demo_FooStatus(in *FooStatus, out *demo.FooStatus, s conversion.Scope) error {
	out.Phase = demo.FooPhase(in.Phase)
	out.Conditions = *(*[]demo.FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_v1alpha1_FooStatus_To_demo_FooStatus is an autogenerated conversion function.
func Convert_v1alpha1_FooStatus_To_demo_FooStatus(in *FooStatus, out *demo.FooStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_FooStatus_To_demo_FooStatus(in, out, s)
}

func autoConvert_demo_FooStatus_To_v1alpha1_FooStatus(in *demo.FooStatus, out *FooStatus, s conversion.Scope) error {
	out.Phase = FooPhase(in.Phase)
	out.Conditions = *(*[]FooCondition)(unsafe.Pointer(&in.Conditions))
	return nil
}

// Convert_demo_FooStatus_To_v1alpha1_FooStatus is an autogenerated conversion function.
func Convert_demo_FooStatus_To_v1alpha1_FooStatus(in *demo.FooStatus, out *FooStatus, s conversion.Scope) error {
	return autoConvert_demo_FooStatus_To_v1alpha1_FooStatus(in, out, s)
}
