apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Service
metadata:
  name: apiserver
  namespace: demo
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 6443
  selector:
    apiserver: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apiserver
  namespace: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  namespace: demo
  labels:
    app: apiserver
    apiserver: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiserver
      apiserver: "true"
  template:
    metadata:
      labels:
        app: apiserver
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
        - name: apiserver
          image: guodoliu/demo-apiserver:1.0.1
          args: ["--etcd-servers=http://localhost:2379", "--enable-etcd-storage=true"]
          imagePullPolicy: Always
        - name: etcd
          image: bitnami/etcd:3.5.9
          env:
            - name: ALLOW_NONE_AUTHENTICATION
              value: "yes"